%Build the metrics table for featuresExtraction_20x main's file
function [contentTable] = buildTable(cystName, numOfCells, fullCyst3dFeatures, hollowTissue3dFeatures, lumen3dFeatures, ~, celularHeight, class, ellipsoidFactor, curvNeg, warnings)

    contentTable = table(cystName, ...
        numOfCells,...
        celularHeight,...
        string(class),...
        ellipsoidFactor,...
        fullCyst3dFeatures.Volume,...
        fullCyst3dFeatures.ConvexVolume,...
        fullCyst3dFeatures.SurfaceArea, ...
        fullCyst3dFeatures.PrincipalAxisLength,...
        fullCyst3dFeatures.normalizedPrincipalAxesLength, ...
        fullCyst3dFeatures.aspectRatio,...
        fullCyst3dFeatures.sphericity,...
        fullCyst3dFeatures.Solidity,...
        fullCyst3dFeatures.irregularityShapeIndex,...
        fullCyst3dFeatures.Volume/numOfCells,...
        fullCyst3dFeatures.SurfaceArea/lumen3dFeatures.SurfaceArea,...
        fullCyst3dFeatures.SurfaceArea/numOfCells,...
        hollowTissue3dFeatures.Volume,...
        hollowTissue3dFeatures.SurfaceArea,...
        hollowTissue3dFeatures.aspectRatio,...
        hollowTissue3dFeatures.sphericity,...
        hollowTissue3dFeatures.Solidity, ...
        hollowTissue3dFeatures.irregularityShapeIndex,...
        hollowTissue3dFeatures.Volume/numOfCells,...
        lumen3dFeatures.Volume, ...
        lumen3dFeatures.ConvexVolume,...
        lumen3dFeatures.SurfaceArea,...
        lumen3dFeatures.PrincipalAxisLength,...
        lumen3dFeatures.aspectRatio,...
        lumen3dFeatures.sphericity,...
        lumen3dFeatures.Solidity, ...
        lumen3dFeatures.irregularityShapeIndex,...
        lumen3dFeatures.Volume/numOfCells,...
        lumen3dFeatures.SurfaceArea/numOfCells,...
        lumen3dFeatures.Volume/fullCyst3dFeatures.Volume,...
        string(curvNeg),...
        string(warnings));
    
    contentTable.Properties.VariableNames = {'cystName',...
        'numOfCells',...
        'celularHeight',...
        'class',...
        'ellipsoidFactor',...
        'cystVolume',...
        'cystConvexVolume',...
        'cystSurfaceArea',...
        'cystPrincipalAxesLength',...
        'cystPrincipalAxesNormalized',...
        'cystAspectRatio',...
        'cystSphericity',...
        'cystSolidity',...
        'cystIrregularityShapeIndex',...
        'cystVolumePerCell',...
        'cystSurfaceRatio',...
        'basalSurfacePerCell',...
        'hollowTissueVolume',...
        'hollowTissueSurfaceArea',...
        'hollowTissueAspectRatio', ...
        'hollowTissueSphericity',...
        'hollowTissueSolidity',...
        'hollowTissueIrregularShapeIndex',...
        'hollowTissueVolumePerCell',...
        'lumenVolume',...
        'lumenConvexVolume',...
        'lumenSurfaceArea',...
        'lumenPrincipalAxesLength',...
        'lumenAspectRatio',...
        'lumenSphericity',...
        'lumenSolidity',...
        'lumenIrregularShapeIndex',...
        'lumenVolumePerCell',...
        'apicalSurfacePerCell',...
        'percentageLumenSpace',...
        'curvNeg',...
        'warnings'};
    
    contentTable.Properties.VariableUnits = {'#',...
        '#',...
        'microns',...
        '#',...
        '#',...
        'cubic microns',...
        'cubic microns',...
        'squared microns',...
        'microns',...
        'microns',...
        '#',...
        '#',...
        '#',...
        '#',...
        'cubic microns',...
        'squared microns',...
        'cubic microns',...
        '#',...
        'squared microns',...
        '#',...
        '#',...
        '#',...
        '#',...
        'cubic microns',...
        'cubic microns',...
        'cubic microns',...
        'squared microns',...
        'microns',...
        '#',...
        '#',...
        '#',...
        '#',...
        'cubic microns',...
        'squared microns',...
        '#',...
        '#',...
        '#'};


end